version: "3.7"

services:
    app:
        image: ${APP_IMAGE}
        container_name: ${APP_NAME}
        build:
            context: ..
            target: development
            dockerfile: .docker/Dockerfile
        volumes:
            - ..:/application
        ports:
          - 8081:8080
        depends_on: 
            - mariadb

    mariadb:
        image: mariadb:10.3
        container_name: ${DB_IMAGE_NAME}
        environment:
            - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
            - MYSQL_DATABASE=${DB_NAME}
            - MYSQL_USER=${DB_USER}
            - MYSQL_PASSWORD=${DB_PASSWORD}
        ports:
            - "8083:3306"
